name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman & HTML reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Newman collection
        run: |
          newman run ./collection.json \
            -r htmlextra \
            --reporter-htmlextra-export ./reports/report.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-report
          path: reports/report.html
